interface types {
    
    use jabratech:black-scholes/types.{calculate-greeks-request};

    record request{
        options: list<calculate-greeks-request>,
        currency: string,
    }

    record snapshot{
        greek: string,
        bs: f64, 
        smile: f64,
    }

    record snapshot-response{
        code: s16,
        message: string,
        data: list<snapshot>,
    }

    record bucket{
        period: string,
        delta: f64, 
        gamma: f64,
        theta: f64,
        vega: f64,
        rho: f64
    }

    record bucket-response{
        code: s16,
        message: string,
        data: list<bucket>,
    }
}